config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  get 'users/logout_path', to: 'users#logout'
  resources :users, only: [:index, :show] do
    collection do
      get 'sold_items'
    end
  end
  resources :credit_cards, only: :new
  resources :items do
    resources :comments, only: [:create, :destroy]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'purchase', to: 'items#purchase'
      get 'pay', to: 'items#pay'
      get 'done', to: 'items#done'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :purchases, only: [:new] do
    collection do
      get 'index', to: 'purchases#index'
      post 'pay', to: 'purchases#pay'
      get 'done', to: 'purchases#done'
    end
  end
  
  resources :credit_cards, only: [:new,:show] do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user

  validates :card_id, presence: true
  validates :customer_id, presence: true
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  require 'payjp'
  before_action :set_card, only: [:show, :delete]


  def new
    credit_card = CreditCard.where(user_id: current_user.id)
    redirect_to action: "show" if credit_card.exists?
  end

  def pay #payjpとcreditcardのテーブル作成
    Payjp.api_key = Rails.application.credentials.pay_jp[:PAY_JP_PRIVATE_KEY]
    if params["payjp-token"].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
        email: current_user.email,
        card: params["payjp-token"],
        metadata: {user_id: current_user.id}
      )
      @credit_card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @credit_card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete

    if @credit_card.present?
      Payjp.api_key = Rails.application.credentials.pay_jp[:PAY_JP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(@credit_card.customer_id)
      customer.delete
      @credit_card.delete
    end
      redirect_to action: "new"
  end

  def show

    if @credit_card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials.pay_jp[:PAY_JP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(@credit_card.customer_id)
      @default_card_information = customer.cards.retrieve(@credit_card.card_id)
    end
  end

  private

  def set_card
    @credit_card = CreditCard.find_by(user_id: current_user.id)
  end

end

app/views/credit_cards/new.html.haml
.CreditCardsNew
  .Wrapper
    %nav.BreadCrumbs
      %ol.BreadCrumbs__list
        %li
          = link_to root_path, class: "BreadCrumbs__list__link" do
            フリマ
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
        %li
          クレジットカード情報登録
    .Main
      = render "users/sidebar"
      
      .Container
        -# 上部タイトル
        %section.Title
          %h2 クレジットカード情報入力
        .Contents
          .Center
            %section.CardInfo
              -# カード番号入力欄
              .CardInfo__content
                = form_tag(pay_credit_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
                  #card_token
                  %h2.CardInfo__content__name
                  %label カード番号
                  %span.CardInfo__content__name__required
                    必須
                .inputField
                  = text_field_tag "number", "", class: "input", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number",autocomplete: "off"
                  -# = form.text_field :number, "", class: "input", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number",autocomplete: "off"
                  %br
                  = image_tag 'https://web-jp-assets.mercdn.net/_next/static/images/visa-91c71914c6ae23d33f896e60bb1e3859.svg', alt:'visa', size:"48x16", class: "VisaIcon"
                  = image_tag 'https://web-jp-assets.mercdn.net/_next/static/images/mastercard-8b5b68c12b7a2fc8619c71f49ef9209b.svg', alt:'mastercard', size:"48x16", class: "MasterCardIcon"
                  = image_tag 'https://web-jp-assets.mercdn.net/_next/static/images/saison-550107415f39b81fa19e87c96486ba20.svg', alt:'saison', size:"48x16", class: "SaisonIcon"
                  = image_tag 'https://web-jp-assets.mercdn.net/_next/static/images/jcb-9ea981d20008c6545aa3afd1b3da9804.svg', alt:'JCB', size:"48x16", class: "JCBIcon"
                  = image_tag 'https://web-jp-assets.mercdn.net/_next/static/images/american_express-4df44c450653b0209850070ea5cf1264.svg', alt:'american_express', size:"48x16", class: "AmexIcon"
                  = image_tag 'https://web-jp-assets.mercdn.net/_next/static/images/dinersclub-3d52fbb4b39dc998f039571f3314bfc7.svg', alt:'dinersclub', size:"48x16", class: "DinersIcon"
                  = image_tag 'https://web-jp-assets.mercdn.net/_next/static/images/discover-879b0b1c9f9a30159f09e9ef492ad349.svg', alt:'discover', size:"48x16", class: "DiscoverIcon"
                  %br
                  .Span_code
                  %label 有効期限
                  %select#exp_month{name: "exp_month", type: "text"}
                    %option{value: ""} --
                    %option{value: "1"}01
                    %option{value: "2"}02
                    %option{value: "3"}03
                    %option{value: "4"}04
                    %option{value: "5"}05
                    %option{value: "6"}06
                    %option{value: "7"}07
                    %option{value: "8"}08
                    %option{value: "9"}09
                    %option{value: "10"}10
                    %option{value: "11"}11
                    %option{value: "12"}12
                  %span 月/
                  %select#exp_year{name: "exp_year", type: "text"}
                    %option{value: ""} --
                    %option{value: "2020"}20
                    %option{value: "2021"}21
                    %option{value: "2022"}22
                    %option{value: "2023"}23
                    %option{value: "2024"}24
                    %option{value: "2025"}25
                    %option{value: "2026"}26
                    %option{value: "2027"}27
                    %option{value: "2028"}28
                    %option{value: "2029"}29
                  %span 年
                  %span.CardInfo__content__name__required
                    必須
                  %br
                  .Span_code
                  %label セキュリティコード
                  %span.CardInfo__content__name__required
                    必須
                .inputField
                  = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
                .CardInfo__content__about
                  .CardInfo__content__about__question
                    = link_to "#", class: "" do
                      = icon('far', 'question-circle',  class: "Main__center__container__question__icon")
                      カード裏面の番号とは？
                .CardInfo__content__sellButton
                  -# #card_token
                  = submit_tag "追加する", class: "buttonBlue", id: "token_submit"
                %h3.CardInfo__content__returnToHome
                  =link_to root_path do
                    もどる
= render partial: "/items/footer"

app/views/credit_cards/show.html.haml
.CreditCardsShow
  .Wrapper
    %nav.BreadCrumbs
      %ol.BreadCrumbs__list
        %li
          = link_to root_path, class: "BreadCrumbs__list__link" do
            フリマ
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
        %li
          クレジットカード情報削除
    .Main
      = render "users/sidebar"
      
      .Container
        -# 上部タイトル
        %section.Title
          %h2 登録クレジットカード情報
        .Contents
          .Center
            %label 登録クレジットカード情報
            %br
            = "**** **** **** " + @default_card_information.last4
            %br
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
            = form_tag(delete_credit_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
              %input{ type: "hidden", name: "card_id", value: "" }
              %button 削除する
            %h3.CardInfo__content__returnToHome
              =link_to root_path do
                もどる
= render partial: "/items/footer"