config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  get 'users/logout_path', to: 'users#logout'
  resources :users, only: [:index, :show] do
    collection do
      get 'sold_items'
    end
  end
  resources :credit_cards, only: :new
  resources :items do
    resources :comments, only: [:create, :destroy]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'purchase', to: 'items#purchase'
      get 'pay', to: 'items#pay'
      get 'done', to: 'items#done'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :purchases, only: [:new] do
    collection do
      get 'index', to: 'purchases#index'
      post 'pay', to: 'purchases#pay'
      get 'done', to: 'purchases#done'
    end
  end
  
  resources :credit_cards, only: [:new,:show] do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :credit_card, dependent: :destroy
  has_many :items
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :bought_items, class_name: 'Item', foreign_key: 'buyer_id'
  has_many :sold_items, class_name: 'Item', foreign_key: 'seller_id'


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX, message: "＠とドメインを含む必要があります"}
  validates :nickname, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 7 }
  validates :family_name, presence: true, format: {with: /\A[ぁ-んァ-ン一-龥]/, message: "全角のみで入力して下さい"}
  validates :first_name, presence: true, format: {with: /\A[ぁ-んァ-ン一-龥]/, message: "全角のみで入力して下さい"}
  validates :family_name_furigana, presence: true, format: {with: /\A[ぁ-んァ-ヶー－]+\z/, message: "全角ひらがな、全角カタカナのみで入力して下さい"}
  validates :first_name_furigana, presence: true, format: {with: /\A[ぁ-んァ-ヶー－]+\z/, message: "全角ひらがな、全角カタカナのみで入力して下さい"}
  validates :birth_day, presence: true
  validates :family_name_to_deliver, presence: true
  validates :first_name_to_deliver, presence: true
  validates :family_name_to_deliver_furigana, presence: true
  validates :first_name_to_deliver_furigana, presence: true
  validates :postal_code, presence: true
  # validates :prefecture, presence: true
  validates :prefecture_id, presence: true
  validates :municipalities, presence: true
  validates :address, presence: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @listed_items = Item.where(seller_id: current_user.id).includes(:item_images).includes(:comments)
  end

  def sold_items
    @sold_items = Item.where(seller_id: current_user.id).includes(:item_images).includes(:comments)
  end

  def show
  end

end

app/views/users/_sidebar.html.haml
.SideBar
  %nav.SideBarNav
    %ul.SidebarNav__list
      %li
        = link_to "/users/#{current_user.id}", class: "SideBarNav__list__item active" do
          マイページ
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          お知らせ
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          やることリスト
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          いいね！一覧
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          出品する
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          下書き一覧
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to users_path, class: "SideBarNav__list__item" do
          出品した商品 - 出品中
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          出品した商品 - 取引中
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to sold_items_users_path, class: "SideBarNav__list__item" do
          出品した商品 - 売却済み
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          購入した商品 - 取引中
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          購入した商品 - 過去の取引
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          ニュース一覧
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          評価一覧
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          ガイド
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          お問い合わせ
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          売上・振込申請
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
    %h2.SideBarNav__listTitle
      設定
    %ul.SidebarNav__list
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          プロフィール
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          発送元・お届け先住所変更
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          支払い方法
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          メール/パスワード
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '#', class: "SideBarNav__list__item" do
          本人情報
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '/credit_cards/new', class: "SideBarNav__list__item" do
          クレジットカード情報登録
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '/credit_cards/show', class: "SideBarNav__list__item" do
          クレジットカード情報削除
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
      %li
        = link_to '/users/logout_path', class: "SideBarNav__list__item" do
          ログアウト
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", '#', class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'

app/views/users/index.html.haml
= render partial: "/items/header_index"
.UsersIndex
  .Wrapper
    %nav.BreadCrumbs
      %ol.BreadCrumbs__list
        %li
          = link_to root_path, class: "BreadCrumbs__list__link" do
            フリマ
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
        %li
          出品中の商品一覧
    .Main
      = render "sidebar"
      .Container
        .TopPage
          .Main
            .PickupContainer
              %h2.PickupContainer__title
                出品中の商品一覧
              %ul.PickupContainer__items
                - @listed_items.each do |listed_item|
                  - if listed_item.buyer_id.blank?
                    %li.PickupContainer__items--item
                      = link_to "/items/#{listed_item.id}" do
                        .Image
                          = image_tag listed_item.item_images.first.src.url, alt: '', height: '150px', width: '220px'
                        .DetailBox
                          .DetailBox__name
                            = listed_item.name
                          .DetailBox__details
                            %ul
                              %li
                                %span ¥
                                = listed_item.price.to_s(:delimited)
                              %li
                                = icon('fa', 'star likeIcon')
                                3
                            %p
                              (税込)
= render partial: "/items/footer"

app/views/users/logout.html.haml
.Logout
  .Wrapper
    %nav.BreadCrumbs
      %ol.BreadCrumbs__list
        %li
          = link_to root_path, class: "BreadCrumbs__list__link" do
            フリマ
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
        %li
          マイページ
    .Main
      = render "sidebar"
      .Container
        -# ログアウトボタン(method: :deleteつける)
        .LogoutSection
          .LogoutSection__buttonField
            = link_to destroy_user_session_path, method: :delete, class: 'LogoutSection__buttonField__button' do
              %button{type: "", class: "buttonBlue"}
                ログアウト
= render partial: "/items/footer"

app/views/users/show.html.haml
= render partial: "/items/header_index"
.UsersShow
  .Wrapper
    %nav.BreadCrumbs
      %ol.BreadCrumbs__list
        %li
          = link_to root_path, class: "BreadCrumbs__list__link" do
            フリマ
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
        %li
          マイページ
    .Main
      = render "sidebar"
      .Container
        -# ユーザー情報
        %section.UserInfo
          = link_to do
            = image_tag 'icon/member_photo_noimage_thumb.png', alt: 'member', height: '60', width: '60'
            %h3.UserInfo__name
              = current_user.nickname
            .UserInfo__numbers
              %h3.UserInfo__number__evaluation
                評価
                %span.UserInfo__number__evaluation__number
                  0
              %h3.UserInfo__number__exhibition
                出品数
                %span.UserInfo__number__exihibition__number
                  0
        -# お知らせとtodo
        %section.NewsAndTodos
          %ul.NewsAndTodos__tabs
            %li.active
              %h3
                = link_to '#' do
                  お知らせ
            %li
              %h3
                = link_to '#' do
                  やることリスト
          .TabContents
            %ul.Notifications
              %li
                = link_to '#', class: 'Notifications__link' do
                  %figure
                    = image_tag 'icon/logoicon.png', alt: 'logo', height: '48', width: '48', class: 'Notifications__link__image'
                  .Notifications__link__body
                    .Notifications__link__body__text
                      購入も出品もしなくてOK！連携するだけで300円分のポイントがもらえる！
                    %time
                      %i
                        = icon('far', 'clock',  class: "icon")
                        %span.date
                          11時間前
                  %i.angleRight
                    = icon('fas', 'angle-right',  class: "icon")
              %li
                = link_to '#', class: 'Notifications__link' do
                  %figure
                    = image_tag 'icon/logoicon.png', alt: 'logo', height: '48', width: '48', class: 'Notifications__link__image'
                  .Notifications__link__body
                    .Notifications__link__body__text
                      購入も出品もしなくてOK！連携するだけで300円分のポイントがもらえる！購入も出品もしなくてOK！連携するだけで300円分のポイントがもらえる！
                    %time
                      %i
                        = icon('far', 'clock',  class: "icon")
                        %span.date
                          11時間前
                  %i.angleRight
                    = icon('fas', 'angle-right',  class: "icon")
              %li
                = link_to '#', class: 'Notifications__link' do
                  %figure
                    = image_tag 'icon/logoicon.png', alt: 'logo', height: '48', width: '48', class: 'Notifications__link__image'
                  .Notifications__link__body
                    .Notifications__link__body__text
                      購入も出品もしなくてOK！連携するだけで300円分のポイントがもらえる！購入も出品もしなくてOK！連携するだけで300円分のポイントがもらえる！購入も出品もしなくてOK！連携するだけで300円分のポイントがもらえる！
                    %time
                      %i
                        = icon('far', 'clock',  class: "icon")
                        %span.date
                          11時間前
                  %i.angleRight
                    = icon('fas', 'angle-right',  class: "icon")
              %li.GoToMypageList
                = link_to '#' do
                  一覧を見る
        %section.PurchasedItems
          %h2.TabIntroduction
            購入した商品
          %ul.PurchasedItems__tabs
            %li.active
              %h3
                = link_to '#' do
                  取引中
            %li
              %h3
                = link_to '#' do
                  過去の取引
          .TabContents
            %ul.TransactionNow
              %li.TransactionNow__notFound
                取引中の商品がありません
= render partial: "/items/footer"

app/views/users/sold_items.html.haml
= render partial: "/items/header_index"
.UsersSoldItems
  .Wrapper
    %nav.BreadCrumbs
      %ol.BreadCrumbs__list
        %li
          = link_to root_path, class: "BreadCrumbs__list__link" do
            フリマ
          %i.angleRight
            = icon('fas', 'angle-right',  class: "icon")
        %li
          売却済みの商品一覧
    .Main
      = render "sidebar"
      .Container
        .TopPage
          .Main
            .PickupContainer
              %h2.PickupContainer__title
                売却済みの商品一覧
              %ul.PickupContainer__items
                - @sold_items.each do |sold_item|
                  - if sold_item.buyer_id.present?
                    %li.PickupContainer__items--item
                      = link_to "/items/#{sold_item.id}" do
                        .Image
                          = image_tag sold_item.item_images.first.src.url, alt: '', height: '150px', width: '220px'
                            -# buyer_idがある（購入された）場合にSOLDのテキストが入る
                            - if sold_item.buyer_id.present?
                            .Sold
                              .Sold__text
                                SOLD
                        .DetailBox
                          .DetailBox__name
                            = sold_item.name
                          .DetailBox__details
                            %ul
                              %li
                                %span ¥
                                = sold_item.price.to_s(:delimited)
                              %li
                                = icon('fa', 'star likeIcon')
                                3
                            %p
                              (税込)
= render partial: "/items/footer"