config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  get 'users/logout_path', to: 'users#logout'
  resources :users, only: [:index, :show] do
    collection do
      get 'sold_items'
    end
  end
  resources :credit_cards, only: :new
  resources :items do
    resources :comments, only: [:create, :destroy]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'purchase', to: 'items#purchase'
      get 'pay', to: 'items#pay'
      get 'done', to: 'items#done'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :purchases, only: [:new] do
    collection do
      get 'index', to: 'purchases#index'
      post 'pay', to: 'purchases#pay'
      get 'done', to: 'purchases#done'
    end
  end
  
  resources :credit_cards, only: [:new,:show] do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :item_images, dependent: :destroy
  belongs_to :category, optional: true
  accepts_nested_attributes_for :item_images, allow_destroy: true
  
  validates_associated :item_images
  validates :item_images, presence: true
  validates :name, presence: true
  validates :explanation, presence: true
  validates :category_id, presence: true
  # brandはバリデーションなし
  validates :item_condition_id, presence: true
  validates :prefecture_id, presence: true
  validates :delivery_fee_id, presence: true
  validates :preparation_day_id, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  


  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :item_condition
  belongs_to_active_hash :delivery_fee
  belongs_to_active_hash :preparation_day
  belongs_to_active_hash :size

  belongs_to :buyer, class_name: "User", foreign_key: "buyer_id", optional: true
  belongs_to :seller, class_name: "User", foreign_key: "seller_id", optional: true

  def self.search(search)
    if search != ""
      Item.where(['name LIKE(?) or explanation LIKE(?)', "%#{search}%", "%#{search}%"])
    else
      Item.all
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  require 'payjp'
  before_action :set_card, only: [:purchase, :pay, :done]

  before_action :move_to_index, except: [:index, :show, :search]
  before_action :category_parent_array, only: [:new, :create, :edit, :update]
  before_action :set_item, only: [:show, :destroy, :purchase, :done, :edit, :update]
  
  def index
    @items = Item.includes(:item_images).limit(3).order('created_at DESC')
    # レディース新着アイテムとメンズ新着アイテム
    @ladies_items = Item.where(category: 159..346).includes(:item_images).limit(3).order("created_at DESC")
    @mens_items = Item.where(category: 347..476).includes(:item_images).limit(3).order("created_at DESC")
  end
  
  def new
    @item = Item.new
    @item.item_images.new
  end

  def purchase
    #テーブルからpayjpの顧客IDを検索
    if @credit_card.blank?
      #登録された情報がない場合にカード登録画面に移動する
      redirect_to controller: "credit_cards", action: "new"
    else
      Payjp.api_key = Rails.application.credentials.pay_jp[:PAY_JP_PRIVATE_KEY]
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(@credit_card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(@credit_card.card_id)
    end
  end

  def pay

    @item = Item.find(params[:id])
    Payjp.api_key = Rails.application.credentials.pay_jp[:PAY_JP_PRIVATE_KEY]
    Payjp::Charge.create(
    amount: @item.price, #支払金額を入力（itemテーブル等に紐づけても良い）
    customer: @credit_card.customer_id, #顧客ID
    currency:'jpy'
  )
  @item.update!(buyer_id: current_user.id)
  redirect_to action: 'done' #完了画面に移動
  end

  def done
  end

  # 以下全て、formatはjsonのみ
  # 親カテゴリが選択された後に動くアクション
  def get_category_children
    # 選択された親カテゴリに紐づく子カテゴリの配列を取得する
    @category_children = Category.find("#{params[:parent_id]}").children
  end
  
  # 子カテゴリが選択された後に動くアクション
  def get_category_grandchildren
    # 選択された子カテゴリに紐づく孫カテゴリの配列を取得する
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end
  
  # 孫カテゴリが選択された後に動くアクション（サイズ）
  def get_size
    selected_grandchild = Category.find("#{params[:grandchild_id]}") 
    if related_size_parent = selected_grandchild.sizes[0] 
      @sizes = related_size_parent.children
    else
      selected_child = Category.find("#{params[:grandchild_id]}").parent
      if related_size_parent = selected_child.sizes[0]
        @sizes = related_size_parent.children
      end
    end
  end
  
  def create
    @item = Item.new(item_params)
    
    if @item.save
      redirect_to root_path
      flash[:notice] = "商品を出品しました"
    else
      render :new
    end
  end

  def edit
    @category_grandchild = @item.category
    @category_child = @category_grandchild.parent
    @category_parent = @category_child.parent
    @size = @item.size
    # カテゴリー一覧を作成
    @category = Category.find(params[:id])
    # 紐づく孫カテゴリーの親（子カテゴリー）の一覧を配列で取得
    @category_children = @item.category.parent.parent.children
    # 紐づく孫カテゴリーの一覧を配列で取得
    @category_grandchildren = @item.category.parent.children
    # サイズ自体が存在しているかどうか
    if @item.size_id.present?
      @sizes = @item.size.parent.children
    end
    @images = ItemImage.where(item_id: params[:id])
  end

  def show
    @item_images = @item.item_images
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
    @category_grandchild = @item.category
    @category_child = @category_grandchild.parent
    @category_parent = @category_child.parent
  end

  def update
    # updateアクションの前でないとうまく動作しない
    # 編集画面で選択された新しいカテゴリー
    @category_grandchild = Category.find(item_params[:category_id])
    @category_child = @category_grandchild.parent
    @category_parent = @category_child.parent
    # sizeがあるかどうか？なければnilを入れる
    if @category_grandchild.sizes.present?
      @item.size_id = @category_grandchild.sizes[0].id
    else
      @item.size = nil
    end

    @size = @item.size
    # カテゴリー一覧を作成
    # @category = Category.find(params[:id])
    # @category = Category.find(item_params[:category_id])
    # 紐づく孫カテゴリーの親（子カテゴリー）の一覧を配列で取得
    @category_children = @item.category.parent.parent.children
    # 紐づく孫カテゴリーの一覧を配列で取得
    @category_grandchildren = @item.category.parent.children
    # サイズ自体が存在しているかどうか
    if @item.size_id.present?
      if @item.size.ancestry.present?
        @sizes = @item.size.parent.children
      else
        @sizes = nil
      end
    else
      @sizes = nil
    end

    # binding.pry
    if @item.update(item_params)
      redirect_to root_path
      flash[:notice] = "商品を編集しました"
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "商品の編集に失敗しました"
    end
  end

  def search
    @search_items = Item.search(params[:key])
  end

  def destroy
    if @item.destroy
      redirect_to root_path
      flash[:notice] = "商品を削除しました"
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "商品の削除に失敗しました"
    end
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :explanation, :category_id, :size_id, :item_condition_id, :prefecture_id, :delivery_fee_id, :preparation_day_id, item_images_attributes: [:src, :_destroy, :id]).merge(seller_id: current_user.id)
  end

  def category_parent_array
    @category_parent_array = Category.where(ancestry: nil)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_card
    # binding.pry
    @credit_card = CreditCard.find_by(user_id: current_user.id)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_destroy.html.haml
.DestroyPage 
  .Success
    %p 削除が完了しました。
    = link_to root_path do
      トップページに戻る

app/views/items/_footer.html.haml
.FooterPage
  .BottomVisual
    .Content
      %h2.Content__title
        だれでもかんたん、人生を変えるフリマアプリ
      %p.Content__text
        今すぐ無料ダウンロード！
      .Content__btn
        .Content__btn--apple
          = link_to '#' do
            = image_tag 'pict/app-store.svg', alt: 'AppStore', width: '180px'
        .Content__btn--google
          = link_to '#' do
            = image_tag 'pict/google-play.svg', alt: 'GooglePlay', width: '180px'
  .Footer
    .Contents
      .Contents__content
        %h2 FURIMAについて
        %ul 
          %li
            = link_to '#' do
              会社概要（運営会社）
          %li
            = link_to '#' do
              プライバシーポリシー
          %li
            = link_to '#' do
              FURIMA利用規約
          %li
            = link_to '#' do
              ポイントに関する特約
      .Contents__content
        %h2 FURIMAを見る
        %ul
          %li
            = link_to '#' do
              カテゴリー一覧
          %li
            = link_to '#' do
              ブランド一覧
      .Contents__content
        %h2 ヘルプ＆ガイド
        %ul 
          %li
            = link_to '#' do
              FURIMAガイド
          %li
            = link_to '#' do
              FURIMAロゴ利用ガイドライン
          %li
            = link_to '#' do
              お知らせ


    .LogoZone
      = link_to root_path do
        = image_tag 'logo/logo-white.png', alt: '', height: '', width: '160px', class: ''
      %p © FURIMA

app/views/items/_header_index.html.haml
%header.Header
  .Header__inner
    .Header__inner__main
      %h1.Header__inner__main__icon
        = link_to root_path, class:"Header__inner__main__icon__link" do
          = image_tag 'logo/logo.png', alt:"ロゴアイコン", class: "Header__inner__main__icon__link__img"
      
      .Header__inner__main__searchbox
        = form_with(url: search_items_path, local: true, method: :get, class: "") do |f|
          -# %input utf8など入る
          = f.text_field :key, placeholder: "キーワードから探す", class: "Header__inner__main__searchbox__input", id: "searchInput"
          %button{type: "submit", class:"search-box-btn"}
            .Header__inner__main__searchbox__input__icon
              = image_tag 'http://furima.tokyo/assets/icon-search-60a83ada85216fe00789cd16065281694d9a08948275fef83683fadcf131d84d.svg', class:"search-btn"
            %input{type: "hidden", name:"AuthenticityToken"}
        %ul.Header__inner__main__searchbox__result
    
    .Header__inner__nav
      %ul.Header__inner__nav__listsleft
        %li.Header__inner__nav__listsleft__item.Header__inner__nav__listsleft__item__first 
          = link_to 'カテゴリー', '#'
        
        %li.Header__inner__nav__listsleft__item
          = link_to 'ブランド', '#'
          -# %ul.burandsPulldown
      
      %ul.Header__inner__nav__listsright
        - unless user_signed_in?
          %li.Header__inner__nav__listsright__item
            = link_to 'ログイン', new_user_session_path, class: "post"
          %li.Header__inner__nav__listsright__item
            = link_to '新規会員登録', new_user_registration_path, class: "post"
        - if user_signed_in?
          %li.Header__inner__nav__listsright__item
            = link_to 'マイページ', "/users/#{current_user.id}"
          %li.Header__inner__nav__listsright__item
            = link_to 'ログアウト', '/users/logout_path'

app/views/items/_item_new_btn.html.haml
= link_to '/items/new' do    
  .PurchaseBtn
    .PurchaseBtn__text
      出品する
    .PurchaseBtn__icon
      = image_tag 'icon/icon_camera.png', alt: '出品する'

app/views/items/done.html.haml
.PurchasesDone
  .MainContainer
    .MainContainer__header
      = link_to items_path, class:"MainContainer__headerLogo" do
        = image_tag 'logo/logo.png', alt: "icon", class:"MainContainer__headerImage"
    .MainContainer__text
      .MainContainer__text__message
        %h2 購入が完了しました！
      .MainContainer__text__item
        %p 商品名
        = @item.name
      .MainContainer__text__price
        %p 支払い金額
        %span ¥
        = @item.price.to_s(:delimited)
      .MainContainer__text__back__toppage
        = link_to 'トップページに戻る', items_path, class:"btn" 

app/views/items/index.html.haml
= render partial: "header_index"
.TopPage
  .Main
    .TopVisual
      .Content
        %h2.Content__title
          <br>人生を変えるフリマアプリ
        %p.Content__text
          FURIMAはだれでもかんたんに出品・購入できる<br>フリマアプリです
        .Content__btn
          .Content__btn--apple
            = link_to '#' do
              = image_tag 'pict/app-store.svg', alt: 'AppStore', width: '180px'
          .Content__btn--google
            = link_to '#' do
              = image_tag 'pict/google-play.svg', alt: 'GooglePlay', width: '180px'

    .Introduction
      %h2.Introduction__title
        FURIMAが選ばれる3つの理由
        .UnderLine
      %ul.Introduction__items
        %li.Introduction__items--item
          .Image
            %span.Number 1
            = image_tag 'pict/pict-reason-01.jpg', alt: '', width: '100%'
          %h3.Subtitle
            %span 3分
            ですぐに出品
          %p.Description スマホで入力するだけで簡単に出品できる！
        %li.Introduction__items--item
          .Image
            %span.Number 2
            = image_tag 'pict/pict-reason-02.jpg', alt: '', width: '100%'
          %h3.Subtitle
            %span シンプル
            で使いやすい
          %p.Description めんどくさい入力は必要なく、検索も購入もスムーズ！
        %li.Introduction__items--item.last
          .Image
            %span.Number 3
            = image_tag 'pict/pict-reason-03.jpg', alt: '', width: '100%'
          %h3.Subtitle
            手数料
            %span 業界最安
          %p.Description 最大3％でお得に出品&購入！

    .MiddleVisual
      .Content
        %h2.Content__title
          会員数日本一位
        %p.Content__text
          FURIMAは、フリマアプリで最も人気。<br>出品・購入回数も業界最多です！<br>ほしかったあの商品に出会えるかもしれません。
        .Content__btn
          .Content__btn--apple
            = link_to '#' do
              = image_tag 'pict/app-store.svg', alt: 'AppStore', width: '180px'
          .Content__btn--google
            = link_to '#' do
              = image_tag 'pict/google-play.svg', alt: 'GooglePlay', width: '180px'



    .Feature
      %h2.Feature__title
        FURIMAの特徴
        .UnderLine
      %ul.Feature__items
        %li.Feature__items--item
          .Image
            = image_tag 'icon/icon-01.png'
          %h3.Subtitle
            簡単に売り買いできる
          %p.Description
            スマホひとつで、いつでもどこでも簡単に出品・購入が可能！

        %li.Feature__items--item
          .Image
            = image_tag 'icon/icon-03.png'
          %h3.Subtitle
            売上金は即日振込みに対応
          %p.Description
            午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!

        %li.Feature__items--item
          .Image
            = image_tag 'icon/icon-04.png'
          %h3.Subtitle
            様々な支払いに対応
          %p.Description
            お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

    .PickupContainer
      %h2.PickupContainer__title
        ピックアップカテゴリー
      %h3.PickupContainer__subtitle
        = link_to '#' do
          新規投稿商品

      %ul.PickupContainer__items
        - @items.each do |item|
          %li.PickupContainer__items--item
            = link_to item_path(item.id) do
              .Image
                = image_tag item.item_images.first.src.url, alt: '', height: '150px', width: '220px'
                  -# buyer_idがある（購入された）場合にSOLDのテキストが入る
                  - if item.buyer_id.present?
                  .Sold
                    .Sold__text
                      SOLD
              .DetailBox
                .DetailBox__name
                  = item.name
                .DetailBox__details
                  %ul
                    %li
                      %span ¥
                      = item.price.to_s(:delimited)
                    %li
                      = icon('fa', 'star likeIcon')
                      3
                  %p
                    (税込)
      %h3.PickupContainer__subtitle
        = link_to '#' do
          レディース新着アイテム
      %ul.PickupContainer__items
        - @ladies_items.each do |ladies_item|
          %li.PickupContainer__items--item
            = link_to item_path(ladies_item.id) do
              .Image
                = image_tag ladies_item.item_images.first.src.url, alt: '', height: '150px', width: '220px'
                  -# buyer_idがある（購入された）場合にSOLDのテキストが入る
                  - if ladies_item.buyer_id.present?
                  .Sold
                    .Sold__text
                      SOLD
              .DetailBox
                .DetailBox__name
                  = ladies_item.name
                .DetailBox__details
                  %ul
                    %li
                      %span ¥
                      = ladies_item.price.to_s(:delimited)
                    %li
                      = icon('fa', 'star likeIcon')
                      3
                  %p
                    (税込)
      %h3.PickupContainer__subtitle
        = link_to '#' do
          メンズ新着アイテム
      %ul.PickupContainer__items
        - @mens_items.each do |mens_item|
          %li.PickupContainer__items--item
            = link_to item_path(mens_item.id) do
              .Image
                = image_tag mens_item.item_images.first.src.url, alt: '', height: '150px', width: '220px'
                  -# buyer_idがある（購入された）場合にSOLDのテキストが入る
                  - if mens_item.buyer_id.present?
                  .Sold
                    .Sold__text
                      SOLD
              .DetailBox
                .DetailBox__name
                  = mens_item.name
                .DetailBox__details
                  %ul
                    %li
                      %span ¥
                      = mens_item.price.to_s(:delimited)
                    %li
                      = icon('fa', 'star likeIcon')
                      3
                  %p
                    (税込)

  = render "footer"
  = render "item_new_btn"

app/views/items/purchase.html.haml
.PurchasesNew
  .MainContainer
    %section.MainContainer__header
      = link_to items_path, class:"MainContainer__headerLogo" do
        = image_tag 'logo/logo.png', alt: "icon", class:"MainContainer__headerImage"
    .MainContainer__purchases
      %section.MainContainer__purchases__details
        %h2.MainContainer__purchases__details__title
          購入内容の確認
      %section.MainContainer__purchases__items
        .MainContainer__purchases__items__inner
          .MainContainer__purchases__items__inner__products
            %h3.MainContainer__purchases__items__inner__products__image
              = image_tag @item.item_images.first.src.url, alt: '画像', height: '100px', width: '100px'
            .MainContainer__purchases__items__inner__products__text
              %p.MainContainer__purchases__items__inner__products__text__name
                = @item.name
              %p.MainContainer__purchases__items__inner__products__text__price
                %span.Shipping__style
                  = @item.delivery_fee.delivery_fee
                %span.Shipping__price ¥
                = @item.price.to_s(:delimited)
      %section.MainContainer__purchases__checkout
        .MainContainer__purchases__checkout__total
          %span
            支払い金額
          %span.TotalPrice ¥
          = @item.price.to_s(:delimited)
        %label.MainContainer__purchases__checkout__points
          -# %label.MainContainer__purchases__checkout__points_use disabled-class
            -# %span.Check_box
              -# %span.Style__input
                -# =image_tag
                %p.MainContainer__purchases__checkout__points__text
                  -# ポイントの使用
          .MainContainer__purchases__checkout__logo
            = image_tag 'icon/logoicon.png', alt:"ロゴアイコン", size: "14x14", class: "Logo"
            %p.MainContainer__purchases__checkout__logo__usePoint
              ポイントの使用
            %p.MainContainer__purchases__checkout__logo__usePoint2
              所持ポイント：P0
      %section.MainContainer__purchases__payMethod
        .MainContainer__purchases__payMethod__inner
          .MainContainer__purchases__payMethod__inner__title
            %h3.MainContainer__purchases__payMethod__inner__title__way
              支払い方法: クレジットカード
            -# = link_to '変更する','#', class: ".MainContainer__purchases__payMethod__inner__title__way__link Change__link"
          .MainContainer__purchases__payMethod__inner__cardInfo
            = "**** **** **** " + @default_card_information.last4
            %br/
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
            %br/
            = image_tag 'https://web-jp-assets.mercdn.net/_next/static/images/visa-91c71914c6ae23d33f896e60bb1e3859.svg', alt:'visaアイコン', size:"48x16", class: "Visa-icon"
      %section.MainContainer__purchases__address
        .MainContainer__purchases__address__inner
          .MainContainer__purchases__address__inner__title
            %h3.MainContainer__purchases__address__inner__title__details
              配送先
            -# = link_to '変更する', '#', class: "MainContainer__purchases__address__inner__title__details__link Change__link"
          .MainContainer__purchases__address__inner__detailAdress
            %p
              %span
                〒
                = current_user.postal_code.to_s.insert(3, "-") #郵便番号にハイフンを入れる
            %p
              = current_user.prefecture.prefecture
              = current_user.municipalities
              = current_user.address
              = current_user.building
            %p
              = current_user.family_name_to_deliver
              = current_user.first_name_to_deliver
      %section.MainContainer__purchases__decide
        .MainContainer__purchases__decide__btn
          = link_to pay_item_path(@item.id) do 
            .MainContainer__purchases__decide__btn__link
              %p 購入する
    

app/views/items/search.html.haml
= render partial: "header_index"
.TopPage
  .Main
    .PickupContainer
      %h2.PickupContainer__title
        検索結果
      %ul.PickupContainer__items
        - @search_items.each do |item|
          %li.PickupContainer__items--item
            = link_to "/items/#{item.id}" do
              .Image
                = image_tag item.item_images.first.src.url, alt: '', height: '150px', width: '220px'
              .DetailBox
                .DetailBox__name
                  = item.name
                .DetailBox__details
                  %ul
                    %li
                      %span ¥
                      = item.price.to_s(:delimited)
                    %li
                      = icon('fa', 'star likeIcon')
                      3
                  %p
                    (税込)

  = render "footer"
  = render "item_new_btn"

app/views/items/show.html.haml
//ヘッダー部分テンプレート
= render partial: "header_index"
//パンクズ部分テンプレート

.Main
  .showMain
    .contentLeftqq
    .contentRight
      .topContent
        .ItemBox
          %h2.ItemBox__name 
            = @item.name
          .ItemBox__body
            %ul
              %li
                = image_tag @item.item_images.first.src.url, alt: 'image1'
                %ul
                  - @item_images.each do |item_image|
                    %li
                      =image_tag item_image.src.url, size: "75x75", alt: "image"
          .ItemBox__price
            %span
              ¥
              = @item.price.to_s(:delimited)
              -# to_s(:delimited)が価格にカンマをいれる記述
            .ItemBox__priceDetail
              %span
                (税込)
              %span
                = @item.delivery_fee.delivery_fee
          -# white-space: pre-wrapで改行やスペースを認識してくれる
          .itemDetail{style: "white-space: pre-wrap;"}
            = @item.explanation
          .table
            %table
              %tbody
                %tr
                  %th 出品者
                  %td 
                    = @item.seller.nickname
                    -# = @item.user.nicknameじゃないよ、class_nameで指定したsellerを使うよ
                %tr
                  %th カテゴリー
                  -# - if [46, 74, 134, 142, 147, 150, 158].include?(@category_id)
                  -#   %td
                  -#     = link_to "#{@category_child.category}","#"
                  -#     %br= link_to "#{@category_grandchild.category}","#" 
                  -# -else
                  %td
                    = link_to "#{@category_parent.category}","#"
                    %br= link_to "#{@category_child.category}","#"
                    = link_to "#{@category_grandchild.category}","#"
                %tr
                  %th ブランド
                  %td
                %tr
                  %th 商品のサイズ
                  %td 
                    = @item&.size&.size
                    -# ぼっち演算子
                %tr
                  %th 商品の状態
                  %td                                         
                    = @item.item_condition.condition
                %tr
                  %th 配送料の負担
                  %td 
                    = @item.delivery_fee.delivery_fee
                %tr
                  %th 発送元の地域
                  %td 
                    = @item.prefecture.prefecture
                %tr
                  %th 発送日の目安
                  %td 
                    = @item.preparation_day.preparation_day
          .optionalArea
            %ul
              %li#likeBtn.optionalBtn.likeBtn
                %i.fa.fa-star
                お気に入り 0
            %ul.optional
              %li.optionalBtn
                =link_to "#" do
                  %i.fa.fa-flag
                  不適切な商品の通報

          - if user_signed_in?  && current_user.id != @item.seller_id
            .PurchaseBox
              = link_to purchase_item_path(@item.id), class: "RemoveUnderLine" do
                .PurchaseButton
                  = icon('fa', 'shopping-cart')
                  この商品を購入する

          - if user_signed_in?  && current_user.id == @item.seller_id
            .EditBox
              = link_to edit_item_path, class: "RemoveUnderLine" do
                .EditBtn
                  = icon('fa', 'edit')
                  この商品を編集する
            .DeleteBox
              = link_to item_path, method: :delete, class: "RemoveUnderLine" do
                .DeleteBtn
                  = icon('fa', 'trash')
                  この商品を削除する

          .CommentBox
            %h1 コメント一覧
            - if @comments
              .CommentList
                - @comments.each do |comment|
                  %ul
                    %li.CommentList__user
                      = comment.user.nickname
                      %span さん
                      - if @item.seller_id== comment.user.id
                        %span (出品者)
                    %li.CommentList__text
                      = comment.text
                    %li.CommentList__delete
                      - if user_signed_in? && current_user.id == comment.user.id
                        = link_to item_comment_path(comment.item.id, comment.id), method: :delete do
                          = icon('fa', 'trash')
            - else
              %p - まだコメントはありません - 
              
            - if user_signed_in?
              .CommentForm
                = form_with model: [@item, @comment], local: true, id: "NewComment" do |f|
                  = f.text_area :text, placeholder: 'コメント入力欄', class: "TextBox"
                  .noticeMsg
                    相手のことを考え丁寧なコメントを心がけましょう。
                    %br/
                    不快な言葉遣いなどは利用制限や退会処分となることがあります。
                  %button.commentBtn{ name: "button", type: "submit", class: "SubmitAJAX" }
                    %i.fa.fa-comment
                    コメントする
            - else
              %p.NotLogin（コメント機能はログイン時のみご利用いただけます。）


      -# %ul.links
        -# %li.left
        -#   =link_to "#" do
        -#     %i.fa.fa-angle-left
        -#     %span
        -#     前の商品
        -# %li.right
        -#   =link_to "#" do
        -#     %span 
        -#     後ろの商品
        -#     %i.fa.fa-angle-right
      -# .relatedItems
        -# =link_to 'メンズをもっと見る', "#"



//フッター部分テンプレート
= render "footer"
= render "item_new_btn"